Hotfix: Remove hass.localize calls causing AttributeError
- Revert to French hardcoded strings to fix immediate crash
- HomeAssistant object does not have localize attribute
- Translation will be handled properly via translation_key in future update

Fixes AttributeError: 'HomeAssistant' object has no attribute 'localize'